### PR TITLE
Create Template_Hnas_Hds

### PR DESCRIPTION
**Pull request by jefferson22alcantara**
Template Hnas  using autodiscovery to monitoring  Cpu , Filesystem Utilization , iops and much more  for nas  Hds systems

### CODE REVIEW

**Comment by jangaraj** [comment]
You are adding template (file) to this repo. It's not correct. You should to add only git module ("link") to some repo, which has this template. See readme.
Thank you.

**Comment by jefferson22alcantara** [comment]
Thanks , I will add the git module

2015-11-03 14:36 GMT-02:00 Jan Garaj <notifications@github.com>:

**Comment by jangaraj** [comment]
I did it - see https://github.com/zabbix/zabbix-community-repos/commit/a0fcdf4ac87fed18d8314da73dea2b3d04873d69

**Comment by jefferson22alcantara** [comment]
thanks

**Pull request closed without merging**
